import {
  User,
  Student,
  Lecture,
  ExtraLecture,
  TimetableVersion,
  ExitApplication,
  ExitPermission,
  QRToken,
  Notification,
  AuditLogEntry,
} from './types';

export const SEED_HOD: User = {
  id: 'usr_hod_1',
  name: 'Dr. Ananya Sharma',
  email: 'hod.cs@exitq.edu',
  role: 'HOD',
  department: 'Computer Science & Engineering',
  title: 'Head of Department',
  avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
  phone: '+91 98765 43210',
};

export const SEED_FACULTY: User[] = [
  {
    id: 'usr_fac_1',
    name: 'Prof. Rajesh Kumar',
    email: 'rajesh.kumar@exitq.edu',
    role: 'FACULTY',
    department: 'Computer Science & Engineering',
    title: 'Associate Professor',
    avatarUrl: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?w=150&auto=format&fit=crop&q=80',
    phone: '+91 98765 43211',
  },
  {
    id: 'usr_fac_2',
    name: 'Prof. Meera Iyer',
    email: 'meera.iyer@exitq.edu',
    role: 'FACULTY',
    department: 'Computer Science & Engineering',
    title: 'Assistant Professor',
    avatarUrl: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80',
    phone: '+91 98765 43212',
  },
  {
    id: 'usr_fac_3',
    name: 'Prof. Vikram Patel',
    email: 'vikram.patel@exitq.edu',
    role: 'FACULTY',
    department: 'Computer Science & Engineering',
    title: 'Assistant Professor',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    phone: '+91 98765 43213',
  },
];

export const SEED_GUARDS: User[] = [
  {
    id: 'usr_grd_1',
    name: 'Ramesh Singh',
    email: 'guard.gate1@exitq.edu',
    role: 'GUARD',
    department: 'Campus Security',
    title: 'Senior Security Officer - Gate 1',
    phone: '+91 98765 43220',
  },
  {
    id: 'usr_grd_2',
    name: 'Suresh Yadav',
    email: 'guard.gate2@exitq.edu',
    role: 'GUARD',
    department: 'Campus Security',
    title: 'Security Officer - Gate 2 (West)',
    phone: '+91 98765 43221',
  },
];

export const SEED_STUDENTS: Student[] = [
  {
    id: 'usr_std_1',
    studentId: 'CS-2023-042',
    name: 'Aarav Mehta',
    email: 'aarav.mehta@student.exitq.edu',
    role: 'STUDENT',
    department: 'Computer Science & Engineering',
    semester: 4,
    batch: 'CS-SEM4',
    isOutside: false,
    teacherGuardianName: 'Prof. Rajesh Kumar',
    teacherGuardianId: 'usr_fac_1',
    attendancePercentage: 88.5,
    totalExits: 6,
    approvedExits: 5,
    rejectedExits: 1,
    cancelledExits: 0,
    avatarUrl: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=150&auto=format&fit=crop&q=80',
    guardian: {
      id: 'gdn_1',
      studentId: 'usr_std_1',
      name: 'Sunil Mehta',
      relation: 'Father',
      phone: '+91 98111 22334',
      email: 'sunil.mehta@gmail.com',
      notificationPreferences: { sms: true, email: true, inApp: true },
    },
  },
  {
    id: 'usr_std_2',
    studentId: 'CS-2023-088',
    name: 'Priya Verma',
    email: 'priya.verma@student.exitq.edu',
    role: 'STUDENT',
    department: 'Computer Science & Engineering',
    semester: 4,
    batch: 'CS-SEM4',
    isOutside: true,
    teacherGuardianName: 'Prof. Meera Iyer',
    teacherGuardianId: 'usr_fac_2',
    attendancePercentage: 92.0,
    totalExits: 4,
    approvedExits: 4,
    rejectedExits: 0,
    cancelledExits: 0,
    avatarUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80',
    guardian: {
      id: 'gdn_2',
      studentId: 'usr_std_2',
      name: 'Kavita Verma',
      relation: 'Mother',
      phone: '+91 98222 33445',
      email: 'kavita.verma@yahoo.com',
      notificationPreferences: { sms: true, email: true, inApp: true },
    },
  },
  {
    id: 'usr_std_3',
    studentId: 'CS-2023-112',
    name: 'Rohan Gupta',
    email: 'rohan.gupta@student.exitq.edu',
    role: 'STUDENT',
    department: 'Computer Science & Engineering',
    semester: 4,
    batch: 'CS-SEM4',
    isOutside: false,
    teacherGuardianName: 'Prof. Rajesh Kumar',
    teacherGuardianId: 'usr_fac_1',
    attendancePercentage: 79.0,
    totalExits: 8,
    approvedExits: 5,
    rejectedExits: 2,
    cancelledExits: 1,
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    guardian: {
      id: 'gdn_3',
      studentId: 'usr_std_3',
      name: 'Rajiv Gupta',
      relation: 'Father',
      phone: '+91 98333 44556',
      email: 'rajiv.gupta@gmail.com',
      notificationPreferences: { sms: true, email: true, inApp: true },
    },
  },
  {
    id: 'usr_std_4',
    studentId: 'CS-2023-015',
    name: 'Ananya Deshmukh',
    email: 'ananya.d@student.exitq.edu',
    role: 'STUDENT',
    department: 'Computer Science & Engineering',
    semester: 4,
    batch: 'CS-SEM4',
    isOutside: false,
    teacherGuardianName: 'Prof. Vikram Patel',
    teacherGuardianId: 'usr_fac_3',
    attendancePercentage: 95.4,
    totalExits: 2,
    approvedExits: 2,
    rejectedExits: 0,
    cancelledExits: 0,
    avatarUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
    guardian: {
      id: 'gdn_4',
      studentId: 'usr_std_4',
      name: 'Sanjay Deshmukh',
      relation: 'Father',
      phone: '+91 98444 55667',
      email: 'sanjay.d@outlook.com',
      notificationPreferences: { sms: true, email: true, inApp: true },
    },
  },
];

export const SEED_LECTURES: Lecture[] = [
  // Monday Schedule
  {
    id: 'lec_1',
    day: 'MON',
    startTime: '10:00',
    endTime: '11:00',
    subject: 'Database Management Systems (DBMS)',
    subjectCode: 'CS401',
    facultyId: 'usr_fac_1',
    facultyName: 'Prof. Rajesh Kumar',
    room: 'Lab 204',
    department: 'Computer Science & Engineering',
    semester: 4,
  },
  {
    id: 'lec_2',
    day: 'MON',
    startTime: '11:00',
    endTime: '12:00',
    subject: 'Operating Systems (OS)',
    subjectCode: 'CS402',
    facultyId: 'usr_fac_2',
    facultyName: 'Prof. Meera Iyer',
    room: 'Hall 301',
    department: 'Computer Science & Engineering',
    semester: 4,
  },
  {
    id: 'lec_3',
    day: 'MON',
    startTime: '12:00',
    endTime: '13:00',
    subject: 'Computer Networks (CN)',
    subjectCode: 'CS403',
    facultyId: 'usr_fac_3',
    facultyName: 'Prof. Vikram Patel',
    room: 'Hall 301',
    department: 'Computer Science & Engineering',
    semester: 4,
  },
  {
    id: 'lec_4',
    day: 'MON',
    startTime: '15:00',
    endTime: '16:00',
    subject: 'Software Engineering (SE)',
    subjectCode: 'CS404',
    facultyId: 'usr_fac_3',
    facultyName: 'Prof. Vikram Patel',
    room: 'Hall 302',
    department: 'Computer Science & Engineering',
    semester: 4,
  },
  // Note: 14:00 - 15:00 is scheduled as FREE in timetable!
];

export const SEED_TIMETABLE_VERSION: TimetableVersion = {
  version: 1,
  modifiedBy: 'usr_hod_1',
  modifiedByName: 'Dr. Ananya Sharma',
  timestamp: '2026-08-28T09:00:00.000Z',
  changeSummary: 'Initial Semester 4 Master Timetable Published',
  lectures: SEED_LECTURES,
};

export const SEED_APPLICATIONS: ExitApplication[] = [
  {
    id: 'EXQ-10495',
    studentId: 'usr_std_1',
    studentName: 'Aarav Mehta',
    studentRoll: 'CS-2023-042',
    department: 'Computer Science & Engineering',
    semester: 4,
    reasonCategory: 'MEDICAL',
    reasonDescription: 'Dental appointment at City Clinic.',
    destination: 'City Health Center, MG Road',
    exitTime: '14:00',
    expectedReturnTime: '16:00',
    date: '2026-08-29',
    accompanyingCount: 1,
    accompanyingStudentIds: ['usr_std_3'],
    accompanyingStudentNames: ['Rohan Gupta'],
    submittedAt: '2026-08-29T10:15:00.000Z',
    status: 'APPROVED_CONDITIONAL',
    permissionType: 'CONDITIONAL',
    hodRemark: 'Approved for 2 students until 4:00 PM. Subject to no extra lectures.',
  },
  {
    id: 'EXQ-10496',
    studentId: 'usr_std_4',
    studentName: 'Ananya Deshmukh',
    studentRoll: 'CS-2023-015',
    department: 'Computer Science & Engineering',
    semester: 4,
    reasonCategory: 'OFFICIAL_WORK',
    reasonDescription: 'Representing college at Inter-College Robotics Symposium.',
    destination: 'IIT Campus Auditorium',
    exitTime: '14:00',
    expectedReturnTime: '17:30',
    date: '2026-08-29',
    accompanyingCount: 0,
    submittedAt: '2026-08-29T09:30:00.000Z',
    status: 'APPROVED_LOCKED',
    permissionType: 'LOCKED',
    hodRemark: 'Official Duty Permission - Protected Status Granted.',
  },
  {
    id: 'EXQ-10492',
    studentId: 'usr_std_2',
    studentName: 'Priya Verma',
    studentRoll: 'CS-2023-088',
    department: 'Computer Science & Engineering',
    semester: 4,
    reasonCategory: 'PERSONAL',
    reasonDescription: 'Passport office appointment for verification.',
    destination: 'Regional Passport Office',
    exitTime: '11:30',
    expectedReturnTime: '15:00',
    date: '2026-08-29',
    accompanyingCount: 0,
    submittedAt: '2026-08-29T08:45:00.000Z',
    status: 'APPROVED_CONDITIONAL',
    permissionType: 'CONDITIONAL',
    hodRemark: 'Allowed for personal work.',
  },
  {
    id: 'EXQ-10490',
    studentId: 'usr_std_3',
    studentName: 'Rohan Gupta',
    studentRoll: 'CS-2023-112',
    department: 'Computer Science & Engineering',
    semester: 4,
    reasonCategory: 'FAMILY_EMERGENCY',
    reasonDescription: 'Collect home keys from parent at main gate.',
    destination: 'Campus Main Gate area',
    exitTime: '09:30',
    expectedReturnTime: '10:00',
    date: '2026-08-29',
    accompanyingCount: 0,
    submittedAt: '2026-08-29T09:00:00.000Z',
    status: 'USED',
    permissionType: 'CONDITIONAL',
    hodRemark: 'Short leave allowed.',
  },
  {
    id: 'EXQ-10488',
    studentId: 'usr_std_1',
    studentName: 'Aarav Mehta',
    studentRoll: 'CS-2023-042',
    department: 'Computer Science & Engineering',
    semester: 4,
    reasonCategory: 'PERSONAL',
    reasonDescription: 'Movie outing with friends.',
    destination: 'City Mall',
    exitTime: '13:00',
    expectedReturnTime: '17:00',
    date: '2026-08-28',
    accompanyingCount: 2,
    submittedAt: '2026-08-28T11:00:00.000Z',
    status: 'REJECTED',
    rejectedReason: 'Non-essential personal outings during lab hours are strictly prohibited.',
  },
];

export const SEED_PERMISSIONS: ExitPermission[] = [
  {
    id: 'PERM-10495',
    applicationId: 'EXQ-10495',
    studentId: 'usr_std_1',
    permissionType: 'CONDITIONAL',
    validFrom: '2026-08-29T14:00:00.000Z',
    validUntil: '2026-08-29T16:00:00.000Z',
    status: 'APPROVED_CONDITIONAL',
    hodRemark: 'Approved for 2 students until 4:00 PM. Subject to no extra lectures.',
    groupCount: 2,
    accompanyingStudentNames: ['Rohan Gupta'],
    qrTokenId: 'qr_tok_10495',
  },
  {
    id: 'PERM-10496',
    applicationId: 'EXQ-10496',
    studentId: 'usr_std_4',
    permissionType: 'LOCKED',
    validFrom: '2026-08-29T14:00:00.000Z',
    validUntil: '2026-08-29T17:30:00.000Z',
    status: 'APPROVED_LOCKED',
    hodRemark: 'Official Duty Permission - Protected Status Granted.',
    groupCount: 1,
    accompanyingStudentNames: [],
    qrTokenId: 'qr_tok_10496',
  },
  {
    id: 'PERM-10492',
    applicationId: 'EXQ-10492',
    studentId: 'usr_std_2',
    permissionType: 'CONDITIONAL',
    validFrom: '2026-08-29T11:30:00.000Z',
    validUntil: '2026-08-29T15:00:00.000Z',
    status: 'APPROVED_CONDITIONAL',
    hodRemark: 'Allowed for personal work.',
    groupCount: 1,
    accompanyingStudentNames: [],
    qrTokenId: 'qr_tok_10492',
    exitTimestamp: '2026-08-29T11:35:00.000Z',
  },
];

export const SEED_QR_TOKENS: QRToken[] = [
  {
    id: 'qr_tok_10495',
    token: 'exq_tok_7f8a9b1c2d3e4f5a6b7c8d9e0f1a2b3c',
    permissionId: 'PERM-10495',
    applicationId: 'EXQ-10495',
    studentId: 'usr_std_1',
    studentName: 'Aarav Mehta',
    expiresAt: '2026-08-29T16:00:00.000Z',
    isUsed: false,
  },
  {
    id: 'qr_tok_10496',
    token: 'exq_tok_1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d',
    permissionId: 'PERM-10496',
    applicationId: 'EXQ-10496',
    studentId: 'usr_std_4',
    studentName: 'Ananya Deshmukh',
    expiresAt: '2026-08-29T17:30:00.000Z',
    isUsed: false,
  },
  {
    id: 'qr_tok_10492',
    token: 'exq_tok_9876543210abcdef9876543210fedcba',
    permissionId: 'PERM-10492',
    applicationId: 'EXQ-10492',
    studentId: 'usr_std_2',
    studentName: 'Priya Verma',
    expiresAt: '2026-08-29T15:00:00.000Z',
    isUsed: true,
    usedAt: '2026-08-29T11:35:00.000Z',
  },
];

export const SEED_NOTIFICATIONS: Notification[] = [
  {
    id: 'notif_1',
    userId: 'usr_std_1',
    userRole: 'STUDENT',
    title: 'Exit Request Granted (Conditional)',
    message: 'Your request EXQ-10495 was approved conditionally by Dr. Ananya Sharma.',
    type: 'SUCCESS',
    category: 'APPLICATION',
    read: false,
    createdAt: '2026-08-29T10:16:00.000Z',
    link: '/student/passes',
  },
  {
    id: 'notif_2',
    userId: 'usr_hod_1',
    userRole: 'HOD',
    title: 'New Pending Application',
    message: 'Aarav Mehta submitted exit application EXQ-10495.',
    type: 'INFO',
    category: 'APPLICATION',
    read: true,
    createdAt: '2026-08-29T10:15:00.000Z',
    link: '/hod/applications/EXQ-10495',
  },
  {
    id: 'notif_3',
    userId: 'usr_std_2',
    userRole: 'STUDENT',
    title: 'Gate Exit Verified',
    message: 'Exit recorded at Gate 1 by Ramesh Singh at 11:35 AM.',
    type: 'INFO',
    category: 'GATE_ACTIVITY',
    read: true,
    createdAt: '2026-08-29T11:35:00.000Z',
  },
];

export const SEED_AUDIT_LOGS: AuditLogEntry[] = [
  {
    id: 'log_1',
    timestamp: '2026-08-29T11:35:04.000Z',
    actorName: 'Ramesh Singh',
    actorRole: 'GUARD',
    actorId: 'usr_grd_1',
    action: 'GATE_SCAN_EXIT',
    target: 'EXQ-10492 (Priya Verma)',
    result: 'SUCCESS',
    reason: 'QR Verified - Timetable clear - Gate 1',
  },
  {
    id: 'log_2',
    timestamp: '2026-08-29T10:16:00.000Z',
    actorName: 'Dr. Ananya Sharma',
    actorRole: 'HOD',
    actorId: 'usr_hod_1',
    action: 'APPLICATION_GRANT',
    target: 'EXQ-10495 (Aarav Mehta)',
    result: 'SUCCESS',
    reason: 'Type: APPROVED_CONDITIONAL | Remark: Approved for 2 students until 4:00 PM.',
  },
  {
    id: 'log_3',
    timestamp: '2026-08-29T10:15:00.000Z',
    actorName: 'Aarav Mehta',
    actorRole: 'STUDENT',
    actorId: 'usr_std_1',
    action: 'APPLICATION_SUBMIT',
    target: 'EXQ-10495',
    result: 'SUCCESS',
    reason: 'Reason: Medical - Dental appointment',
  },
];
